version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
      - ..:/usr/share/nginx/html
    ports:
      - 80:80
    links:
      - php

  php:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ..:/usr/share/nginx/html
    links:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=YES
    ports:
      - 3306:3306

  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    restart: always
    hostname: myRabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root